### PR TITLE
fix: constrain quicheLogVerbose value

### PR DESCRIPTION
**Pull request by achingbrain**
The valid values [are](https://fuchsia.googlesource.com/third_party/abseil-cpp/+/refs/tags/20230125.3/absl/base/log_severity.h#69) -1 | 0 | 1 | 2 | 3 so cause a type error if anything else is passed.

### CODE REVIEW

**Comment by achingbrain** [comment]
It might be these ones? https://fuchsia.googlesource.com/third_party/abseil-cpp/+/refs/tags/20230125.3/absl/base/log_severity.h#69

**Comment by martenrichter** [comment]
Yes, this must be the one, and -1 is off. It is the default.

**Comment by achingbrain** [comment]
The types here are hard to use because the `WebTransportBase` constructor [takes a WebTransportOptions](https://github.com/fails-components/webtransport/blob/master/main/lib/webtransportbase.js#L26) rather than a [HttpWebTransportInit](https://github.com/fails-components/webtransport/blob/master/main/lib/types.ts#L269) so the `quicheLogVerbose` isn't a valid option.

It needs to be added to the [WebTransportOptions interface](https://github.com/fails-components/webtransport/blob/master/main/lib/dom.ts#L74) which I see already has some non-standard options defined in it.

FWIW most of `dom.js` can be removed now since the `WebTransport` types are defined in TypeScript's DOM typings which they weren't back when `dom.js` was added.

**Comment by martenrichter** [comment]
> The types here are hard to use because the `WebTransportBase` constructor [takes a WebTransportOptions](https://github.com/fails-components/webtransport/blob/master/main/lib/webtransportbase.js#L26) rather than a [HttpWebTransportInit](https://github.com/fails-components/webtransport/blob/master/main/lib/types.ts#L269) so the `quicheLogVerbose` isn't a valid option.

So far, I did not consider it a public interface..., but feel free to add it in a pact.

> 
> It needs to be added to the [WebTransportOptions interface](https://github.com/fails-components/webtransport/blob/master/main/lib/dom.ts#L74) which I see already has some non-standard options defined in it.
> 
> FWIW most of `dom.js` can be removed now since the `WebTransport` types are defined in TypeScript's DOM typings which they weren't back when `dom.js` was added.

I do not think so. The WebTransport spec changes very often, so I would have missing properties. So it is better to keep it, as it will for sure miss some of the new options.

**Comment by achingbrain** [comment]
In that case it might be better to extend the built-in types to add new properties rather than redefining them?

Otherwise you can end up in all sorts of trouble when some field three levels down in an interface has a type that's missing a `null` or some other trivial thing.

**Comment by martenrichter** [comment]
> Otherwise you can end up in all sorts of trouble when some field three levels down in an interface has a type that's missing a `null` or some other trivial thing.
Precisely, this happens already with the Streams, where the definition from node.js is slightly different from the dom one.
And as this is the only project, I come in touch with types, it is taking too much time.

**Comment by achingbrain** [comment]
The Node.js types are quite tedious, yes.  They are written by the community though, sometimes you have to PR [DefinitelyTyped/DefinitelyTyped/types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node), but the maintainers there are at least pretty good about merging PRs quickly.

**Pull request merged**
